name: Build and Release

on:
  push:
    branches: [ build/beta ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build frontend
        run: |
          cd frontend
          npm install -g yarn
          yarn set version latest
          yarn install
          yarn run build:prod
          cd ..

      # @TODO Run tests

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./django_react/**/*.py
            ./frontend/**/*.py
            ./core/**/*.py
            ./*/static/**/*
            ./*/templates/**/*.html
            ./*.py
            ./requirements.txt
            ./README.md

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: 'release/beta'
          fetch-depth: 0

      - name: Remove files
        run: |
          rm -rf *
          rm -rf .idea
          rm -rf .github
          rm -f .gitignore

      - name: Acquire artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Add files to git
        run: |
          git add -A
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic deployment
          commit_options: '--no-verify --signoff'
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
